# Generated by Django 4.0.5 on 2022-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Distributor', 'Distributor'), ('Patient', 'Patient'), ('Super Admin', 'Super Admin')], max_length=20, null=True, verbose_name='Account Type'),
        ),
    ]
