# Generated by Django 3.2.7 on 2023-12-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientsData',
            new_name='EnquiryData',
        ),
    ]
