# Generated by Django 3.2.7 on 2023-12-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_patientsdata_enquirydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquirydata',
            old_name='description',
            new_name='message',
        ),
    ]
