# Generated by Django 3.2 on 2023-05-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_auto_20230508_1751'),
        ('master', '0002_masterbranddata_masterformulareferencedata_masterpackagingtypedata_mastervendordata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterBrandData',
        ),
        migrations.DeleteModel(
            name='MasterFormulaReferenceData',
        ),
        migrations.DeleteModel(
            name='MasterPackagingTypeData',
        ),
        migrations.DeleteModel(
            name='MasterVendorData',
        ),
    ]
