# Generated by Django 3.2.7 on 2023-05-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20230508_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterBrandData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterFormulaReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPackagingTypeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterVendorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('reference', models.TextField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
