# Generated by Django 3.2.7 on 2023-12-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20230508_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterBrandData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterPackagingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
