# Generated by Django 3.2.7 on 2023-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_materbranddata_materpackagingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
