# Generated by Django 3.2.7 on 2023-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_materreferencedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterVendorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('reference', models.TextField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
