# Generated by Django 3.2.7 on 2024-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20231212_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFormulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulation_type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
