# Generated by Django 3.2.7 on 2024-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_masterformulationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterformulationdata',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('Qty', 'Qty'), ('Drop', 'Drop'), ('ml', 'ml'), ('gram', 'gram'), ('mg', 'mg'), ('cup', 'cup')], max_length=255, null=True),
        ),
    ]
