# Generated by Django 3.2.7 on 2024-01-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdata',
            old_name='order_date',
            new_name='order_datee',
        ),
    ]
