# Generated by Django 3.2.7 on 2024-01-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_order_date_orderdata_order_datee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdata',
            old_name='order_datee',
            new_name='order_date',
        ),
    ]
