# Generated by Django 3.2.7 on 2024-02-01 18:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20221205_1314'),
        ('drugs', '0017_auto_20231230_1559'),
        ('inventory', '0003_rename_order_datee_orderdata_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('item_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount before Discount', max_digits=11)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Final Amount', max_digits=11)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='discount amount', max_digits=11)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('discount_type', models.CharField(choices=[('Percent Discount', 'Percent Discount'), ('Flat Discount', 'Flat Discount')], default='Percent Discount', max_length=20, verbose_name='discount_type')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patient.patientsdata')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='patient',
        ),
        migrations.AlterField(
            model_name='orderdetailsdata',
            name='order_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_data', to='inventory.orderdata'),
        ),
        migrations.AlterField(
            model_name='orderdetailsdata',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='purchase/selling price', max_digits=11),
        ),
        migrations.CreateModel(
            name='InvoiceDetailsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='purchase/selling price', max_digits=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_drug', to='drugs.drugdata')),
                ('invoice_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_data', to='inventory.invoicedata')),
            ],
        ),
    ]
