# Generated by Django 3.2.7 on 2024-02-01 19:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20240201_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetailsdata',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='invoicedetailsdata',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='MRP', max_digits=11),
        ),
        migrations.AddField(
            model_name='invoicedetailsdata',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='selling price', max_digits=11),
        ),
    ]
