# Generated by Django 3.2.7 on 2024-02-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_invoicedata_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetailsdata',
            name='invoice_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_data', to='inventory.invoicedata'),
        ),
        migrations.AlterField(
            model_name='orderdetailsdata',
            name='order_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_data', to='inventory.orderdata'),
        ),
    ]
