# Generated by Django 3.2.7 on 2024-02-13 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20240202_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsdata',
            name='available_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetailsdata',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='orderdetailsdata',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
