# Generated by Django 3.2.7 on 2024-02-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20240214_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetailsdata',
            name='order_items',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.orderdetailsdata'),
            preserve_default=False,
        ),
    ]
