# Generated by Django 3.2.7 on 2024-02-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_invoicedetailsdata_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetailsdata',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
