# Generated by Django 4.0.5 on 2022-07-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsdata',
            name='medical_reg_no',
        ),
    ]
