# Generated by Django 4.0.5 on 2022-09-15 11:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0003_doctorsdata_gender'),
        ('drugs', '0003_drugdata_mrp'),
        ('patient', '0002_remove_patientsdata_medical_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsdata',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('history_of_chief_complaint', models.TextField()),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_sugar', models.PositiveIntegerField(default=0)),
                ('plus_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('spo2', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('oe', models.TextField(blank=True, help_text='on examination', null=True)),
                ('required_test', models.TextField(blank=True, null=True)),
                ('advise', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_record', to='doctor.doctorsdata')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_record', to='patient.patientsdata')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(blank=True, max_length=10, null=True)),
                ('frequency', models.CharField(blank=True, max_length=10, null=True)),
                ('qty', models.CharField(blank=True, max_length=10, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_drug', to='drugs.drugdata')),
                ('treatment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_prescription', to='patient.treatmentrecord')),
            ],
        ),
    ]
