# Generated by Django 3.2 on 2022-11-14 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patientsdata_user_treatmentrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='diet_exercise',
            field=models.TextField(blank=True, help_text='on examination', null=True),
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11),
        ),
    ]
