# Generated by Django 3.2 on 2022-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20221114_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='dose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
