# Generated by Django 3.2 on 2022-12-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20221205_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='dose',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='frequency',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionrecord',
            name='qty',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
