# Generated by Django 3.2.7 on 2024-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20221205_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsdata',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='patientsdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientsdata',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientsdata',
            name='patient_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientsdata',
            name='patient_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientsdata',
            name='patient_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='blood_sugar',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='history_of_chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
