# Generated by Django 4.0.5 on 2022-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=255, null=True)),
                ('formula', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('drug_unit', models.CharField(choices=[('Qty', 'Qty'), ('Drop', 'Drop'), ('ml', 'ml'), ('gram', 'gram'), ('mg', 'mg'), ('cup', 'cup')], max_length=255)),
                ('Anupana', models.CharField(max_length=150)),
                ('formulation', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
