# Generated by Django 4.0.5 on 2022-07-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugdata',
            old_name='Anupana',
            new_name='anupana',
        ),
    ]
