# Generated by Django 3.2 on 2022-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_drugdata_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugdata',
            name='anupana',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='drugdata',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drugdata',
            name='drug_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drugdata',
            name='drug_unit',
            field=models.CharField(blank=True, choices=[('Qty', 'Qty'), ('Drop', 'Drop'), ('ml', 'ml'), ('gram', 'gram'), ('mg', 'mg'), ('cup', 'cup')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drugdata',
            name='formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drugdata',
            name='formulation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
