# Generated by Django 3.2 on 2022-09-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_auto_20220918_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugdata',
            old_name='anupana',
            new_name='anupaan',
        ),
    ]
