# Generated by Django 3.2 on 2023-05-08 12:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0007_drugdata_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderdata',
            name='vendor',
        ),
        migrations.RenameField(
            model_name='drugdata',
            old_name='name',
            new_name='drug_name',
        ),
        migrations.RemoveField(
            model_name='drugdata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='drugdata',
            name='drug_type',
        ),
        migrations.RemoveField(
            model_name='drugdata',
            name='formula_reference',
        ),
        migrations.RemoveField(
            model_name='drugdata',
            name='packaging_type',
        ),
        migrations.AddField(
            model_name='drugdata',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11),
        ),
        migrations.AlterField(
            model_name='drugdata',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseItemData',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderData',
        ),
    ]
