# Generated by Django 3.2.7 on 2023-05-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_masterbranddata_masterformulareferencedata_masterpackagingtypedata_mastervendordata'),
        ('drugs', '0008_auto_20230508_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugdata',
            old_name='drug_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='drugdata',
            name='mrp',
        ),
        migrations.AddField(
            model_name='drugdata',
            name='category',
            field=models.CharField(choices=[('Drug', 'Drug'), ('Instrument', 'Instrument')], default='Drug', max_length=255),
        ),
        migrations.AddField(
            model_name='drugdata',
            name='drug_type',
            field=models.CharField(blank=True, choices=[('Qty', 'Qty'), ('Drop', 'Drop')], default='Qty', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drugdata',
            name='formula_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_brand', to='master.masterformulareferencedata'),
        ),
        migrations.AddField(
            model_name='drugdata',
            name='packaging_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_type', to='master.masterpackagingtypedata'),
        ),
        migrations.AlterField(
            model_name='drugdata',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_brand', to='master.masterbranddata'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('drug_unit', models.CharField(blank=True, choices=[('Qty', 'Qty'), ('Drop', 'Drop'), ('ml', 'ml'), ('gram', 'gram'), ('mg', 'mg'), ('cup', 'cup')], max_length=255, null=True)),
                ('comment', models.TextField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_brand', to='master.mastervendordata')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(blank=True, max_length=150, null=True)),
                ('purchase_price', models.FloatField(default=0, help_text='unit purchase price')),
                ('mrp', models.FloatField(default=0, help_text='unit item MRP')),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_brand', to='drugs.drugdata')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_brand', to='drugs.purchaseorderdata')),
            ],
        ),
    ]
