# Generated by Django 3.2.7 on 2023-12-08 19:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_matervendordata'),
        ('drugs', '0008_auto_20230508_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vendor', to='master.matervendordata')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=11)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_drug', to='drugs.drugdata')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='drugs.purchaseorderdata')),
            ],
        ),
    ]
