# Generated by Django 3.2.7 on 2023-06-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0009_auto_20230531_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderdata',
            name='drug_unit',
        ),
    ]
