# Generated by Django 3.2.7 on 2023-12-13 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_alter_purchaseorderitemdata_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdata',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
