# Generated by Django 3.2.7 on 2023-12-13 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0013_alter_purchaseorderdata_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdata',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 13, 13, 15, 14, 216206, tzinfo=utc), null=True),
        ),
    ]
