# Generated by Django 3.2.7 on 2023-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0015_alter_purchaseorderdata_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitemdata',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
