# Generated by Django 3.2.7 on 2024-02-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0017_auto_20231230_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugdata',
            name='brand',
        ),
    ]
