# Generated by Django 3.2.7 on 2024-02-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20231212_1546'),
        ('drugs', '0018_remove_drugdata_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdata',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drug_brand', to='master.masterbranddata'),
            preserve_default=False,
        ),
    ]
