# Generated by Django 3.2.7 on 2024-02-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_masterformulationdata_unit_type'),
        ('drugs', '0019_drugdata_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugdata',
            name='anupaan',
        ),
        migrations.RemoveField(
            model_name='drugdata',
            name='drug_unit',
        ),
        migrations.RemoveField(
            model_name='drugdata',
            name='formulation',
        ),
        migrations.RemoveField(
            model_name='drugdata',
            name='mrp',
        ),
        migrations.AddField(
            model_name='drugdata',
            name='formulation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_formulation', to='master.masterformulationdata'),
        ),
    ]
