# Generated by Django 4.0.5 on 2022-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctorsdata_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Other', 'Other')], default='Male', max_length=100),
            preserve_default=False,
        ),
    ]
